#!/bin/bash

#case 1
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.61 --nSwap=1 --policy=DBDP"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.6  --nSwap=1 --policy=DBDP"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.59 --nSwap=1 --policy=DBDP"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.58 --nSwap=1 --policy=DBDP"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.56 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.55 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.52 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.5 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.4 --nSwap=1 --policy=DBDP"

time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.63 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.62 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.61 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.6  --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.58 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.55 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.5  --policy=LDF"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.4  --policy=LDF"

time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.46 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.45 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.44 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.42 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.4  --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.35 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.3  --policy=FCSMA"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=1 --alpha=0.2  --policy=FCSMA"

#case 2
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.93 --nSwap=1 --policy=DBDP"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.92 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.91 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.9  --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.88 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.85 --nSwap=1 --policy=DBDP"

#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.95 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.94 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.93 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.92 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.90 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.85 --nSwap=1 --policy=LDF"

time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.85 --nSwap=1 --policy=FCSMA"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.84 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.83 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.82 --nSwap=1 --policy=FCSMA"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.81 --nSwap=1 --policy=FCSMA"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.8  --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.78 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.76 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.75 --nSwap=1 --policy=FCSMA"

#case 3
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.76 --q=0.9 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.75 --q=0.9 --nSwap=1 --policy=DBDP"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.74 --q=0.9 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.73 --q=0.9 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.72 --q=0.9 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.7  --q=0.9 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.65 --q=0.9 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.6  --q=0.9 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.5  --q=0.9 --nSwap=1 --policy=DBDP"

time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.77 --q=0.9 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.76 --q=0.9 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.75 --q=0.9 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.74 --q=0.9 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.72 --q=0.9 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.7  --q=0.9 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.65 --q=0.9 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.6  --q=0.9 --nSwap=1 --policy=LDF"

#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.52 --q=0.9 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.51 --q=0.9 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.5  --q=0.9  --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.48 --q=0.9 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.45 --q=0.9 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.42 --q=0.9 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=3 --alpha=0.4  --q=0.9 --nSwap=1 --policy=FCSMA"

#case 4
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.94 --nSwap=1 --policy=DBDP"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.93 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.92 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.91 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.9  --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.88 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.85 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.8 --nSwap=1 --policy=DBDP"

#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.94 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.93 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.92 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.90 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.88 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.85 --nSwap=1 --policy=LDF"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.8 --nSwap=1 --policy=LDF"

time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.82  --nSwap=1 --policy=FCSMA"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.81  --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.8  --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.79 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.78 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.76 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.74 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.72 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=4 --alpha=0.7 --q=0.7  --nSwap=1 --policy=FCSMA"

#case 5
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.82  --q=0.99 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.81  --q=0.99 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.8  --q=0.99 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.78 --q=0.99 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.76 --q=0.99 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.74 --q=0.99 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.7  --q=0.99 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.6  --q=0.99 --nSwap=1 --policy=DBDP"

#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.83 --q=0.99 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.82 --q=0.99 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.8  --q=0.99 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.78 --q=0.99 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.76 --q=0.99 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.74 --q=0.99 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.7  --q=0.99 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.6  --q=0.99 --nSwap=1 --policy=DBDP"

#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.36 --q=0.99 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.35 --q=0.99 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.33 --q=0.99 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.3  --q=0.99 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.27 --q=0.99 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.24 --q=0.99 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.2  --q=0.99 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=5 --lambda=0.1  --q=0.99 --nSwap=1 --policy=FCSMA"

#case 6
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.997 --nSwap=1 --policy=DBDP"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.995 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.99 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.98  --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.97 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.95 --nSwap=1 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.9  --nSwap=1 --policy=DBDP"

#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.997 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.995 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.99 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.98 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.97 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.95 --nSwap=1 --policy=LDF"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.9  --nSwap=1 --policy=LDF"

#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.86  --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.85  --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.84 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.83 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.82  --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.81 --nSwap=1 --policy=FCSMA"
#time ./waf --run "scratch/RT-decentralized --nIntervals=20000 --testId=6 --lambda=0.78 --q=0.8  --nSwap=1 --policy=FCSMA"


#case 2 multiple swaps
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.93 --nSwap=2 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.92 --nSwap=2 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.91 --nSwap=2 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.9  --nSwap=2 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.88 --nSwap=2 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.85 --nSwap=2 --policy=DBDP"

time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.93 --nSwap=3 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.92 --nSwap=3 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.91 --nSwap=3 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.9  --nSwap=3 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.88 --nSwap=3 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.85 --nSwap=3 --policy=DBDP"

time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.93 --nSwap=4 --policy=DBDP"
#time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.92 --nSwap=4 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.91 --nSwap=4 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.9  --nSwap=4 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.88 --nSwap=4 --policy=DBDP"
time ./waf --run "scratch/RT-decentralized --nIntervals=5000 --testId=2 --alpha=0.55 --q=0.85 --nSwap=4 --policy=DBDP"
